### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by stevetoro** [koko8puff/prj-rev-bwfs-dasmoto#5]
Satisfactory 👍 

Nice job reproducing the design mock and writing some clean and organized HTML & CSS code in the process. 

Make sure to go back and make better use of the `div` tag so that you can keep your code base logically organized and divided. Likewise, make sure to go back and refactor your CSS to eliminate unnecessary repetition.

**Comment by koko8puff** [comment]
Thanks. I added div tags and refactored my css.
