### ISSUE TITLE
Page sections

### ISSUE THREAD

**Issue by stevetoro** [koko8puff/prj-rev-bwfs-dasmoto#6]
https://github.com/koko8puff/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L12-L19

Wrap a `div` around each main section so that you can properly divide the page into sections. 

Give each of the three main `div`s the class `product` (for example) instead since there are three equivalent product sections . You can give an ID to the `h2` tag in each section since those are the only ones that need to be handled uniquely. This will help you write more descriptive and concise CSS selectors. 

```html
<div class="product">
    <h2 class="brushes">Brushes</h2>
    <img src="./resources/brushes.jpeg"/>
    <h3>Hacksaw Brushes</h3>
    <p>Made of the highest quality oak, Hacksaw brushes are known for their
      weight and ability to hold paint in large amounts. Available in different
      sizes.
    <span class="price">Starting at $3.00 / brush.<span>
    </p>
</div>
```

**Comment by koko8puff** [comment]
I updated my code to incorporate your review notes.
